/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: 3609689cf5cb70837a622998835dd164)
interface __BaseEnv_Env {
	BAIBAI_SERVING: R2Bucket;
	ASSETS: Fetcher;
	VIEW_PASSWORD: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
