/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: 1e84eb7de31901750ac3379cd6d5668b)
interface __BaseEnv_Env {
	BAIBAI_SERVING: R2Bucket;
	ASSETS: Fetcher;
	VIEW_PASSWORD: string;
	READ_ACCESS_TOKEN: string;
	L1_R2_BASE_URL: string;
	L1_R2_ACCESS_KEY_ID: string;
	L1_R2_SECRET_ACCESS_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
